Refactor/register
BitByte-TPC/alumni pull request #86
Opened 2022-04-06 14:01 UTC by Saksham-1508

2022-06-07 11:13 UTC, divyanshkhetan requested changes
Also please resolve your merge conflicts apart from the requested changes. Thanks!

2022-06-09 08:12 UTC, Saksham-1508 commented on templates/AlumniConnect/registration_form.html
> +<button type="submit" class="btn btn-primary">Submit</button>
I've added the changes to make the form responsive

2022-06-09 08:12 UTC, Saksham-1508 commented on templates/AlumniConnect/registration_form.html
> +            <input type="checkbox" name="checkbox_update" class="checkboxinput form-check-input" required=""
Done

2024-01-14 18:30 UTC, garg3133 commented
Added this as part of #122.

Thanks, @Saksham-1508 for this new page and @divyanshkhetan for reviews.

2024-01-14 18:30 UTC, closed without merging